DROP DATABASE IF EXISTS JIS_Database;
CREATE DATABASE JIS_Database;
USE JIS_Database;

CREATE TABLE Clients(
TIN INT(9) UNSIGNED ZEROFILL NOT NULL,
Name VARCHAR(30) NOT NULL, 
Address VARCHAR(50),
Email VARCHAR(64),
Owner_Name VARCHAR(30),
Client_Type CHAR(8) NOT NULL,
PRIMARY KEY(TIN)
);

CREATE TABLE Tel_No(
ID INT NOT NULL AUTO_INCREMENT,
Tel_No INT(10) UNSIGNED,
TIN INT(9) UNSIGNED ZEROFILL NOT NULL REFERENCES Clients(TIN),
PRIMARY KEY (ID)
);

CREATE TABLE Fax_No(
ID INT NOT NULL AUTO_INCREMENT,
Fax_No INT(10) UNSIGNED,
TIN INT(9) UNSIGNED ZEROFILL NOT NULL REFERENCES Clients(TIN),
PRIMARY KEY (ID)
);

CREATE TABLE ITEM(
Model_No VARCHAR(12) NOT NULL DEFAULT 0,
Description VARCHAR(20) NOT NULL,
Price DECIMAL(8,2),
Quantity INT(6),
Storage_Location VARCHAR(30),
PRIMARY KEY(Model_No)
);

CREATE TABLE Invoice(
Invoice_No INT(8) UNSIGNED NOT NULL DEFAULT 0, 
Customer_Name VARCHAR(30) NOT NULL REFERENCES Clients(Name),
Delivery_Address VARCHAR(50),
Customer_PO INT(10) UNSIGNED,
Total_Price DECIMAL(10,2),
PRIMARY KEY(Invoice_No)
);

CREATE TABLE Invoice_Quantity(
Invoice_No INT(8) UNSIGNED NOT NULL DEFAULT 0 REFERENCES Invoice(Invoice_No),
Model_No VARCHAR(12) NOT NULL DEFAULT 0 REFERENCES Item(Model_No),
Quantity INT(6) UNSIGNED,
Unit VARCHAR(8),
Final_Price DECIMAL(9,2),
CONSTRAINT Invoice_Quantity_No PRIMARY KEY (Invoice_No, Model_No)
);

CREATE TABLE Discount_Invoice(
Discount_No INT(2) UNSIGNED NOT NULL,
Discount_Rate INT(5) UNSIGNED,
Invoice_No INT(6) UNSIGNED NOT NULL DEFAULT 0 REFERENCES Invoice_Quantity(Invoice_No),
Model_No VARCHAR(12) NOT NULL DEFAULT 0 REFERENCES Item(Model_No),
CONSTRAINT Discount_Invoice_No PRIMARY KEY (Discount_No, Invoice_No, Model_No)
);

CREATE TABLE Purchase_Order(
PO_No INT(6) UNSIGNED NOT NULL,
Supplier_Name VARCHAR(30) NOT NULL REFERENCES Clients(Name),
Total_Price DECIMAL(10,2),
PRIMARY KEY (PO_No)
);

CREATE TABLE PO_Quantity(
PO_No INT(6) UNSIGNED NOT NULL REFERENCES Purchase_Order(PO_No),
Model_No VARCHAR(12) NOT NULL DEFAULT 0 REFERENCES Item(Model_No),
Quantity INT(6) UNSIGNED,
Unit VARCHAR(8),
Final_Price DECIMAL(9,2),
CONSTRAINT PO_Quantity_No PRIMARY KEY (PO_No, Model_No)
);

CREATE TABLE Discount_PO(
Discount_No INT(2) UNSIGNED NOT NULL,
Discount_Rate INT(5) UNSIGNED,
PO_No INT(6) UNSIGNED NOT NULL REFERENCES PO_Quantity(PO_No),
Model_No VARCHAR(12) NOT NULL DEFAULT 0 REFERENCES Item(Model_No),
CONSTRAINT Discount_PO_No PRIMARY KEY (Discount_No, PO_No, Model_No)
);